### ISSUE TITLE
Several missing GWPs and REs in species_info.csv

### ISSUE THREAD

**Issue by mrghg** [mrghg/py12box#7]
Make sure all this information is consistent with 2018 OA, and add appropriate comment header

**Comment by mrghg** [comment]
Perhaps we should just remove these columns, as they aren't essential to run the model, and they keep changing...

**Comment by lukewestern** [comment]
There are also going to be some updates in the 2022 assessment (I have the preliminary numbers), perhaps worth waiting until the updated annex becomes finalised.
